# Generated by Django 3.0 on 2020-10-04 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_experience', models.FloatField()),
                ('location', models.CharField(max_length=64)),
                ('annual_ctc', models.FloatField()),
                ('linked_in_profile', models.URLField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Designation')),
                ('employment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.EmploymentType')),
                ('tech_stack', models.ManyToManyField(to='common.TechStack')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='common.User')),
            ],
        ),
    ]
