# Generated by Django 3.0 on 2020-10-04 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employmenttype',
            old_name='employement_type',
            new_name='employment_type',
        ),
    ]
